# Generated by Django 5.0 on 2023-12-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0002_rename_bookingdate_booking_booking_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
